# Callback functions

> A callback is a function passed as an argument to another function

> then caller function has responsibility to call that function

```javascript
// example 1st

function getSum(a, b, callback) {
  callback(a + b);
}

function display(num) {
  console.log(num);
}

getSum(3, 4, display);
// here display is callback function which is passed as argument and get called inside getSum() function
```

```javascript
//example 2nd
console.log("before");

getUser(1, function (user) {
  console.log(user);
});

console.log("after");

function getUser(id, callBackFunction) {
  let user = { id, name: "shubham" };

  setTimeout(() => callBackFunction(user), 2000);
}
//here we directly pass the CB to getUser()
// getUser() working Async type due to callback function
```

## callback hell problem

> means complex nested callbacks

```javascript
console.log("before");

getUser(1, function (user) {
  console.log(user);
});

console.log("after");

function getUser(id, callBackFunction) {
  let user = { id, name: "shubham" };

  setTimeout(() => callBackFunction(user), 2000);

  getGitHubRepo(user.name, function (repo) {
    console.log(repo);

    getComments(repo[0], function (comments) {
      console.log(comments);
    });
  });
}

function getGitHubRepo(gitHubUserName, cb) {
  setTimeout(() => cb([1, 2, 34, 4]), 2000);
}

function getComments(repo, cb) {
  setTimeout(() => cb(["comment1", "comment2", "comment3"]), 2000);
}
```

> To deal with this kind of nesting, Js use event queue and promises

# Promise

> Object which holds the result or output of asynchronours activity

> asynchronous method returns a promise to supply the value at some point in the future

> A Promise is in one of these states

1. pending: initial state, neither fulfilled nor rejected.
2. fulfilled: meaning that the operation was completed successfully.
3. rejected: meaning that the operation failed.

```javascript
// promise resolved
// promise rejected

const promise = new Promise((resolve, reject) => {
  // setTimeout(()=>resolve(1),2000);
  setTimeout(() => reject({ message: "something faild" }), 2000);
});
//promise object created using new Promise()
//
promise
  .then((response) => console.log(response)) //when promise resolved , then() is executed
  .catch((err) => console.log(err.message)); //when promise rejected catch() is executed
```

```javascript
console.log("before");

getUser(1)
  .then((response) => console.log(response))
  .catch((err) => console.log(err));
//getUser() method returns promise which is handled

console.log("after");

function getUser(id) {
  return new Promise((resolve, reject) => {
    // setTimeout(() => resolve({ id, name: "shubham" }), 2000);

    setTimeout(() => reject({ message: "somthig going wrong..." }));
  });
}
```

## nested promises

```javascript
console.log("before");

getUser(1)
  .then((response) => {
    console.log(response);
    getGitHubRepo(response.name)
      .then((response) => {
        console.log(response);
        getComments(response[0])
          .then((response) => console.log(response))
          .catch((err) => console.log(err.message));
      })
      .catch((err) => {
        console.log(err.message);
      });
  })
  .catch((err) => console.log(err));

console.log("after");

function getUser(id) {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve({ id, name: "shubham" }), 2000);

    // setTimeout(()=> reject({message:"somthig going wrong..."}));
  });
}

function getGitHubRepo(gitHubUserName) {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(["repo1", "repo2", "repo3"]), 2000);
    // setTimeout(() =>reject({message:"repos not fetched"}), 2000);
  });
}

function getComments(repo) {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(["comment1", "comment2", "comment3"]));
    // setTimeout(()=> reject({message:"comments not fetched...."}));
  });
}
```

## above code in different form

```javascript
console.log("before");

getUser(1)
  .then((response) =>
    getGitHubRepo(response.name).then((response) =>
      getComments(response[0]).then((response) => console.log(response))
    )
  )
  .catch((err) => console.log(err.message));

console.log("after");

function getUser(id) {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve({ id, name: "shubham" }), 2000);

    // setTimeout(()=> reject({message:"somthig going wrong..."}));
  });
}

function getGitHubRepo(gitHubUserName) {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(["repo1", "repo2", "repo3"]), 2000);
    // setTimeout(() =>reject({message:"repos not fetched"}), 2000);
  });
}

function getComments(repo) {
  return new Promise((resolve, reject) => {
    // setTimeout(() => resolve(["comment1", "comment2", "comment3"]));
    setTimeout(() => reject({ message: "comments not fetched...." }));
  });
}
```

# async-await

> these two specially used to work with promimises

> helps to execute synchronous code Asynchronously

> await wont come without async

```javascript
console.log("before");

//always wrap await code inside async function
async function displayComments() {
  try {
    const user = await getUser(1);
    const repo = await getGitHubRepo(user.name);
    const comments = await getComments(repo[0]);
    console.log(comments);
  } catch (err) {
    console.log(err.message);
  }
  // ideal way to handle await methods
  // using try-catch block we can handle error object in catch-block
}

displayComments();

console.log("after");

function getUser(id) {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve({ id, name: "shubham" }), 2000);

    // setTimeout(()=> reject({message:"somthig going wrong..."}));
  });
}

function getGitHubRepo(gitHubUserName) {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(["repo1", "repo2", "repo3"]), 2000);
    // setTimeout(() =>reject({message:"repos not fetched"}), 2000);
  });
}

function getComments(repo) {
  return new Promise((resolve, reject) => {
    // setTimeout(() => resolve(["comment1", "comment2", "comment3"]));
    setTimeout(() => reject({ message: "comments not fetched...." }));
  });
}
```
